# Generated by Django 3.0.8 on 2020-07-17 12:11

from django.db import migrations, models
import processlogs.apps.apachelogs.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(help_text='IP адрес хоста в лог файле', verbose_name='IPv4 address')),
                ('date_logged', models.DateTimeField(verbose_name='Datetime of log')),
                ('url', models.CharField(max_length=500, verbose_name='URL of response')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('CONNECT', 'CONNECT'), ('TRACE', 'TRACE'), ('UNKNOWN', 'UNKNOWN')], default=processlogs.apps.apachelogs.constants.HTTPMethods['UNKNOWN'], max_length=10, verbose_name='HTTP method')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP response status code')),
                ('content_length', models.PositiveIntegerField(verbose_name='Content-Length')),
            ],
        ),
    ]
