# Generated by Django 3.0.8 on 2020-07-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apachelogs', '0002_brokenlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='url',
            field=models.CharField(max_length=10000, verbose_name='URL of response'),
        ),
    ]
